Resolves TypeError on Mac cairo 1.16.0_5
TypeError: Surface.write_to_png takes one argument which must be a filename, file object, or a file-like object which has a "write" method (like BytesIO) taking bytes